<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Calculator.cs" />
    <Compile Remove="ElectricBill.cs" />
    <Compile Remove="ViTrung.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Calculator.cs" />
    <None Include="ElectricBill.cs" />
    <None Include="ViTrung.cs" />
  </ItemGroup>

</Project>
